In [20]:
import kagglehub
import pandas as pd
import numpy as np
import torch

# Download latest version
path = kagglehub.dataset_download("uciml/iris")

print("Path to dataset files:", path)

Path to dataset files: /Users/fredymata/.cache/kagglehub/datasets/uciml/iris/versions/2

In [21]:
iris = pd.read_csv(path + "/Iris.csv")
# iris.head()
# iris.info()
# iris.describe()
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [22]:
# convert to numpy arrays
iris = iris.to_numpy()

In [23]:
def one_hot_encode(y: np.ndarray):
    classes = np.unique(y)
    # save label as key to have O(1) lookup of one hot values
    class_to_index = {label: idx for idx, label in enumerate(classes)}
    y_int = np.array([class_to_index[label] for label in y])  # new array of one hot values
    # Create a one-hot encoded matrix by selecting rows from the identity matrix using the class indices
    return np.eye(len(classes))[y_int]

In [24]:
# separate features and targets
X = iris[:, 1:-1]  # skip first and last column
y = iris[:, -1]  # last column

X = X.astype(float)  # convert from object (str) to floats
y = one_hot_encode(y)